### PR TITLE
Prepare for Share Extension

### PR DESCRIPTION
**Pull request by prashantvc**
- Added the embedded library to share code (ImgurFx)
- Refactor code to make it easily shareable
- Now we can change the image description for an uploading image by setting the description property on the ImageurUpload object

### CODE REVIEW

**Comment by mileswd** [comment]
Thank you :+1:

**Comment by PunKeel** [comment]
I hate you, can't merge this into my project. 

Thanks! :)

**Comment by mileswd** [comment]
@prashantvc Just so you know, I have made some modifications in fdb7fe175edce2e235732a9d2795e63bf6d9297d which further detaches ImgurFx from the main codebase - hopefully this should make it a little easier to work with :)

**Comment by prashantvc** [comment]
@mileswd Thanks! Your changes will certainly make it easier to work with ImgurFx. I am still learning the Swift btw :)

**Comment by mileswd** [comment]
@prashantvc I have recently made some large changes to this project to improve stability and I thought it would be courteous to explain my changes in 0c52206ce403ffff8bba187dce812c141357e746:

I've done a little more research into the use of frameworks and I don't think that having a separate framework for accessing the ImgurAPI is ideal:
- Frameworks add additional overhead in terms of both bundle size and dynamic dispatch
- ImgurFx only consists of two Swift source files

I think it is better to add any required source files to `Build Phases` -> `Compile Sources`
This makes them fully accessible to the project, without having to create a framework.

Irregardless, your contributions are still very much appreciated :)

**Comment by prashantvc** [comment]
@mileswd Yup, it makes to keep things simple :)
I have been bug with the work and did not make much progress with Share feature, so it will be easy to merge your changes

**Pull request merged**
