### PR TITLE
Added option to randomize the name before the upload

### PR DESCRIPTION
**Pull request by Coriou**
I love and use this little app daily but it always bothered me that it
kept the original file name.

Just added an option, unchecked by default, to randomize the name of
the file before uploading it.

It’s the very first time I open a Swift project, so I took no risk and
kept everything naively simple. Implementation might be a bit rough
though. Also, I’m not sure wether I should commit the Pod files, but
their path is not in the gitignore so I guess I do ?

I added the required method in a separate file because if I come up
with the time to read a bit about the language I’d also like to
implement an Exif & ICC cleaner.

### CODE REVIEW

**Comment by mileswd** [comment]
Looks great considering it's your first Swift project! 🎉

It's probably best to only make changes the CocoaPods when the modification you are making requires a change to the project dependencies. The rationale behind storing (or not storing) `/Pods` in Git is available [here](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control).

Quick question - what is the advantage of using a randomised string, as opposed to not supplying a title? ([The title parameter is optional.](https://api.imgur.com/endpoints/image#image-upload))

Thank you for your efforts! 👍

<sup>P.S. [Imgur strips EXIF](https://help.imgur.com/hc/en-us/articles/201746817-Post-Album-and-Image-Privacy)</sup>

**Comment by Coriou** [comment]
Hey, thanks !

Well I did read the article about having - or not - the pods in Git a bit after I posted this pull request. I did read about the language and I also noticed later that imgur was stripping exif data !! 

What I didn't know however, is that the title was optional... Honestly, it didn't even cross my mind. I thought the title was mandatory, to mimic a filename. But since it isn't, there's no advantage of using a randomized string really...

On my own branch I changed the app cast, and tried to publish new releases (I mean technically it worked) just to see because I was really interested in seeing how the Sparkle updater worked. But I really do not suggest you merge this branch at all. Instead, maybe you could just implement the "no title" option. Or I could do it maybe.

**Comment by mileswd** [comment]
> On my own branch I changed the app cast, and tried to publish new releases (I mean technically it worked) just to see because I was really interested in seeing how the Sparkle updater worked. But I really do not suggest you merge this branch at all. Instead, maybe you could just implement the "no title" option. Or I could do it maybe.

Don't worry, it was the Swift code changes I was commenting on 😄

I'll happily accept a revised PR, if you're still interested in this feature :+1:

**Comment by Coriou** [comment]
#120 :)

**Pull request closed without merging**
